name: générer l'image du "serpent des contributions"

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Travaux pour mettre à jour les données
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: |
            src/github-serpent-de-contributions.svg
            src/github-serpent-de-contributions-sombre.svg?palette=github-dark

      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: update
          build_dir: src
          commit_message: mettre à jour le serpent des contributions ;P
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
