name: générer l'image du "serpent des contributions"

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Travaux pour mettre à jour les données
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            src/github-serpent-de-contributions.svg
            src/github-serpent-de-contributions-sombre.svg?palette=github-dark

      - uses: EndBug/add-and-commit@v9
        with:
          add: src
          message: mettre à jour le serpent des contributions ;P
